WebUi/Models/RemotePlayer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using GameLibrary.Engine;
using GameLibrary.Models;
using GameLibrary.Models.Events;
using GameLibrary.Scripting;

using Newtonsoft.Json;

using WebUi.Websockets;

namespace WebUi.Models {
    public class RemotePlayer {
        private readonly string _source;
        private readonly ObjFunction _topLevel;
        private readonly IList<WebsocketConnection> _connections;
        private readonly WebsocketReporter _reporter;

        public int Id { get; init; }

        public RemotePlayer(int id,  string source ) {
            _reporter = new WebsocketReporter(this);
            _connections = new List<WebsocketConnection>();
            _source = source;
            Id  = id;
            ObjFunction? compiled = new Compiler(_source, _reporter).Compile();
            if (compiled == null) {
                throw new RuntimeError("Script can't compile");
            }
            _topLevel = compiled;
        }

        public void AddConnection(WebsocketConnection conn) {
            lock (_connections) {
                _connections.Add(conn);
                conn.MessageReceived += HandleReceivedMessage;
            }
        }

        public void RemoveConnection(WebsocketConnection conn) {
            lock (_connections) {
                conn.MessageReceived -= HandleReceivedMessage;
                _connections.Remove(conn);
            }
        }

        public void HandleReceivedMessage(object? source, string message) {

        }

        public void SendMessage(object json) {
            SendMessage(JsonConvert.SerializeObject(json));
        }

        public void SendMessage(string message) {
            lock (_connections) {
                foreach (WebsocketConnection c in _connections) {
                    c.Send(message);
                }
            }
        }

        public void HandleGameEvent(object? source, GameEvent e) {
            switch (e) {
            case ProductionEvent pe: {
                ObjFunction? handler = _topLevel.GetChild("OnProduction");
                if (handler != null) {
                    handler.Call(_reporter, Value.FromInstance(new ScriptBridge(pe)));
                }
                break;
            }
            case TickEvent te: {
                ObjFunction? handler = _topLevel.GetChild("OnTick");
                if (handler != null) {
                    handler.Call(_reporter, Value.FromInstance(new ScriptBridge(te)));
                }
                break;
            }
            }
            SendMessage(e);
        } 

        private class WebsocketReporter : IReporter {

            private readonly RemotePlayer _player;

            public WebsocketReporter(RemotePlayer player) {
                _player = player;
            }

            public void Error(string message) => _player.SendMessage(new {Type= "Error", Message  = message});
            public void Error(string message, Exception ex) => _player.SendMessage(new { Type = "Error", Message = ex.Message });
            public void Print(Value value) => _player.SendMessage(new { Type = "Print", Message = value.ToString() });
        }
    }
}

WebUi/ViewModels/IndustryVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using GameLibrary.Models;

namespace WebUi.ViewModels {
    public class IndustryVM {

        public IndustryVM(Industry model) {
            Name = model.Name;
            Consumes = model.Consumes;
            Produces = model.Produces;

        }

        public string Name { get; }
        public IDictionary<Resource, long> Consumes { get; }
        public IDictionary<Resource, long> Produces { get; }

    }
}

WebUi/ViewModels/ScriptResult.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WebUi.ViewModels {

    public class ScriptResult {
        [Required]
        public string? Script { get; set; }

        public ScriptStatus Status { get; set; } = ScriptStatus.NotRun;

        public string? PrintText { get; set; }

        public string? ErrorText { get; set; }

        public string? Code { get; set; }

        public Exception? Exception { get; set; }

    }
    public enum ScriptStatus {
        NotRun,
        Ok,
        CompileError,
        RuntimeError,
    }

}

WebUi/ViewModels/StarSystemVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using GameLibrary.Models;

namespace WebUi.ViewModels {
    public class StarSystemVM {

        public StarSystemVM(StarSystem model)  {
            Name = model.Name;

            Properties = new Dictionary<string, long> {
                { nameof(model.Population), model.Population },
                { nameof(model.Technology), model.Technology },
                { nameof(model.Environment), model.Environment }
            };

            Resources = model.SystemResources;

            Stockpile = model.Warehouses.ViewContents;

            Industries = model.Industries.Select(i => new IndustryVM(i)).ToList();
        }

        public string Name { get; }

        public IReadOnlyDictionary<string, long> Properties { get;  }

        public IReadOnlyList<Resource> Resources { get;  }

        public IReadOnlyDictionary<Resource, long> Stockpile { get; }

        public IReadOnlyList<IndustryVM> Industries { get; }
    }
}

WebUi/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using GameLibrary.Engine;

using Microsoft.AspNetCore.Mvc;

namespace WebUi.Controllers {

    [Route("admin")]
    public class AdminController : Controller {

        private readonly GameEngine _engine;

        public AdminController(GameEngine engine) {
            _engine = engine;
        }

        [HttpPost("tick")]
        public IActionResult Tick() {
            _engine.Tick();

            return NoContent();
        }
    }
}

WebUi/Controllers/HomeController.cs
using System.Linq;

using GameLibrary.Engine;

using Microsoft.AspNetCore.Mvc;

using WebUi.ViewModels;

namespace WebUi.Controllers {
    public class HomeController : Controller {

        private readonly GameEngine _engine;

        public HomeController(GameEngine engine) {
            _engine = engine;
        }

        [HttpGet("")]
        //public IActionResult Index() => View(_engine);
        public IActionResult Index() => View("Ants");


        [HttpGet("/state")]
        [Produces("application/json")]
        public IActionResult State() {

            return Ok(_engine.Systems.Select(s =>new StarSystemVM(s) ).ToDictionary(s => s.Name));

        }
    }
}

WebUi/Controllers/ScriptController.cs
using System;

using GameLibrary.Scripting;

using Microsoft.AspNetCore.Mvc;

using WebUi.Lib;
using WebUi.ViewModels;

namespace WebUi.Controllers {

    [Route("/script")]
    public class ScriptController : Controller {

        [HttpGet("")]
        public IActionResult Index() {
            return View(new ScriptResult { Script = "" });
        }

        [HttpPost("")]
        public IActionResult Run(ScriptResult model) {

            if (!ModelState.IsValid) {
                return View("Index", model);
            }

            if (model.Script is null) {
                //Should have been caught by the validity check above
                throw new NullReferenceException();
            }

            CaptureReporter r = new CaptureReporter();

            ObjFunction? topLevel = new Compiler(model.Script, r).Compile();

            if (topLevel == null) {
                model.Status = ScriptStatus.CompileError;
                model.ErrorText = r.ErrorText;
                return View("Index", model);
            }

            string code = Disassembler.Disassemble(topLevel);
            try {
                new VM(r).Interpret(topLevel);
            } catch (Exception ex) {
                model.Status = ScriptStatus.RuntimeError;
                model.ErrorText = r.ErrorText;
                model.Exception = ex;
                return View("Index", model);
            }


            model.Status = ScriptStatus.Ok;
            model.PrintText = r.PrintText;
            model.Code = code;
            return View("Index", model);
        }
    }
}

WebUi/Views/Home/Ants.cshtml
<main>
    <canvas width="800" height="800"></canvas>
</main>
<script type="module">
    import { $ } from './common.js';
    import { Ant } from './ant.js';

    function init() {

        const a = new Ant(200, 200, 0.25 / 2);
        const $canvas = $("canvas");
        const g = $canvas.getContext("2d");

        let moveCounter = 0;

        function m() {
            moveCounter += 1;
            if (moveCounter % 10 == 0) {
                if (Math.random() > 0.5) {
                    a.turnLeft().then(m);
                } else {
                    a.turnRight().then(m);
                }
            } else {
                a.move().then(m);
            }
        }

        m();

        let start;
        function tick(timestamp) {

            if (start === undefined) {
                start = timestamp;
            }

            const elapsed = (timestamp - start) / 1000;
            start = timestamp;

            a.tick(elapsed);

            // Update gaphics
            g.clearRect(0, 0, $canvas.width, $canvas.height)
            a.draw(g);
            requestAnimationFrame(tick);
        }

        requestAnimationFrame(tick);
    }

    window.addEventListener("load", init);
</script>

WebUi/Views/Home/Index.cshtml
@model GameEngine
<nav id="controls" class="box">
    <button id="tick-cmd">Tick</button>
    <span id="tick-count">@Model.TickNumber</span>
</nav>
<main>
    <div id="systems"></div>
</main>

<footer>
    <fieldset id="log" class="box">
        <legend>Mesage Log</legend>
    </fieldset> 
</footer>
<script type="module" src="~/main.js" ></script>

WebUi/Views/Script/Index.cshtml
@model ScriptResult
@{
    ViewBag.Title = "Script Sandbox";
}

<header>

    <h1>@ViewBag.Title</h1>
</header>
<main>

    @switch (Model.Status) {
    case ScriptStatus.Ok:
        <h2>Success!</h2>
        <div>@Model.PrintText</div>
        @if (!string.IsNullOrWhiteSpace(Model.Code)) {
            <h3>Info</h3>
            <div><pre>@Model.Code</pre></div>
        }
        break;
    case ScriptStatus.CompileError:
        <h2>CompileError</h2>
        <div>@Model.ErrorText</div>
        break;
    case ScriptStatus.RuntimeError:
        <h2>Runtime Error</h2>
        <div>@Model.ErrorText</div>
        if (Model.Exception is not null) {
            <div>@Model.Exception.Message</div>
        }
        break;
    }


    <form asp-action="Run" method="post" asp-controller="Script">

        <label asp-for="Script"></label>
        <textarea rows="25" cols="80" asp-for="Script">@Model.Script</textarea>

        <button type="submit">Run script</button>
    </form>

</main>

WebUi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-gb">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/main.css" type="text/css" />
    <link rel="stylesheet" href="~/animation.css" type="text/css" />
    <title>@ViewBag.Title</title>
</head>
<body>
    @RenderBody()
</body>
</html>